modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "ctsadvfix"
version = "${version}"
displayName = "creators-adventure-fix"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.ctsadvfix]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctsadvfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ctsadvfix]]
modId = "architectury"
mandatory = true
versionRange = "[*,)"
ordering = "AFTER"
side = "BOTH"

# Xray 在客户端
[[dependencies.ctsadvfix]]
modId = "atianxray"
mandatory = true
versionRange = "[*,)"
ordering = "AFTER"
side = "CLIENT"

# TinyMobFarm 在两端
[[dependencies.ctsadvfix]]
modId = "tinymobfarm"
mandatory = true
versionRange = "[*,)"
ordering = "AFTER"
side = "BOTH"

# FTB Ultimine 在两端
[[dependencies.ctsadvfix]]
modId = "ftbultimine"
mandatory = true
versionRange = "[*,)"
ordering = "AFTER"
side = "BOTH"
